language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - npm install -g firebase-tools
  - npm install -g yarn
install:
  - yarn
script:
  - yarn build

after_success:
  - travis_wait 40 npm run build
  - firebase use default --token $FIREBASE_TOKEN
  - travis_wait firebase deploy -m "Travis auto-deploy PR ${TRAVIS_PULL_REQUEST}" --non-interactive --token $FIREBASE_TOKEN

branches:
  only:
    - master
