language: node_js
node_js:
- '9'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: "${TRAVIS_BUILD_DIR}/build"
    on:
      branch: master
